/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfa.bancos.Panels;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pfa.bancos.dal.AsaltosDAL;
import pfa.bancos.dal.CondenasDAL;
import pfa.bancos.dal.DelincuentesDAL;
import pfa.bancos.dal.JuecesDAL;
import pfa.bancos.dal.SucursalDAL;
import pfa.bancos.model.Asalto;
import pfa.bancos.model.Condena;
import pfa.bancos.model.Delincuente;
import pfa.bancos.model.Juez;
import pfa.bancos.model.Sucursal;


/**
 *
 * @author Brian
 */
public class AsaltosAddFrame extends javax.swing.JFrame {
    int asaltoId;
    Asalto asalto;
    /**
     * Creates new form AsaltosAddFrame
     */
    public AsaltosAddFrame() {
        initComponents();
        Image icono = Toolkit.getDefaultToolkit().getImage("pfaIcon.png");
        this.setIconImage(icono);     
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        
        SucursalDAL sDAL = new SucursalDAL();
        ArrayList<Sucursal> sucursales = sDAL.getSucursales();        
        for(Sucursal sucursal : sucursales)
        {
            sucursalesCombo.addItem(sucursal.getCodigo());
        }
        
        JuecesDAL jDAL = new JuecesDAL();
        ArrayList<Juez> jueces = jDAL.getJueces();        
        for(Juez juez : jueces)
        {
            JuecesCombo.addItem(juez.getCodigo());
        }
        
        loadDelincuentes();
    }
    
    public void loadDelincuentes()
    {
        DelincuentesDAL dDAL = new DelincuentesDAL();        
        ArrayList<Delincuente> delincuentes = dDAL.getDelincuentes();
        delincuentesCombo.removeAllItems();
        delincuentesCombo.addItem("Seleccione Delincuente");
        for(Delincuente delincuente : delincuentes)
        {
            Boolean agregarDelincuente = true;
            DefaultTableModel model = (DefaultTableModel)delincuentesTable.getModel();            
            for(int i = 0; i < delincuentesTable.getRowCount(); i++)
            {
                if(model.getValueAt(i, 0).toString().equals(delincuente.getCodigo()))
                {
                    agregarDelincuente = false;
                    break;
                }
            }
            if(agregarDelincuente)
            {
                delincuentesCombo.addItem(delincuente.getCodigo());
            }
        }
        agregarCondenaBtn.setEnabled(false);
        quitarCondenaBtn.setEnabled(false);
    }
    
    public AsaltosAddFrame(Asalto asalto)
    {
        this();
        Image icono = Toolkit.getDefaultToolkit().getImage("pfaIcon.png");
        this.setIconImage(icono);     
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        
        JuecesCombo.setSelectedItem(asalto.getCodigoJuez());
        sucursalesCombo.setSelectedItem(asalto.getCodigoSucursal());
        
        fechaTextField.setText(asalto.getFecha().toString());
        
        asaltoId = asalto.getId();
        
        DelincuentesDAL dDAL = new DelincuentesDAL();
        
        for(Delincuente delincuente : dDAL.getPorAsalto(asalto.getId()))
        {
            DefaultTableModel model = (DefaultTableModel)delincuentesTable.getModel();            
            model.addRow(new Object[] { delincuente.getCodigo(), delincuente.getNombre(), delincuente.getCodigoBanda(), delincuente.getDetenido()});
        }
        
        CondenasDAL cDAL = new CondenasDAL();
        
        for(Condena condena : cDAL.getCondenasPorAsalto(asalto.getId()))
        {
            DefaultTableModel model = (DefaultTableModel)condenasTable.getModel();            
            model.addRow(new Object[] { condena.getCodigoDelDelincuente(), condena.getFechaDeInicio(), condena.getFechaFin()});
        }
        
        crearBtn.setText("Guardar");
        agregarCondenaBtn.setEnabled(true);
        quitarCondenaBtn.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sucursalesCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        JuecesCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        delincuentesTable = new javax.swing.JTable();
        agregarDelincuenteBtn = new javax.swing.JButton();
        quitarDelincuente = new javax.swing.JButton();
        delincuentesCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        crearBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        fechaTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        quitarCondenaBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        condenasTable = new javax.swing.JTable();
        agregarCondenaBtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fecha");

        jLabel2.setText("Sucursal");

        sucursalesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));

        jLabel3.setText("Juez");

        JuecesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Delincuentes Participantes");

        delincuentesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Banda", "Detenido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(delincuentesTable);

        agregarDelincuenteBtn.setText("Agregar");
        agregarDelincuenteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDelincuenteBtnActionPerformed(evt);
            }
        });

        quitarDelincuente.setText("Quitar");
        quitarDelincuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarDelincuenteActionPerformed(evt);
            }
        });

        jLabel5.setText("Delincuente:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Datos del Asalto");

        crearBtn.setText("Crear");
        crearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Condenas");

        quitarCondenaBtn.setText("Quitar");
        quitarCondenaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarCondenaBtnActionPerformed(evt);
            }
        });

        condenasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Delincuente", "Fecha Inicio", "Fecha Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(condenasTable);

        agregarCondenaBtn.setText("Agregar");
        agregarCondenaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCondenaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delincuentesCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarDelincuenteBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quitarDelincuente))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregarCondenaBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quitarCondenaBtn))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sucursalesCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JuecesCombo, 0, 200, Short.MAX_VALUE)
                                    .addComponent(fechaTextField)))
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(crearBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelarBtn)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fechaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sucursalesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JuecesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitarDelincuente)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarDelincuenteBtn)
                    .addComponent(delincuentesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitarCondenaBtn)
                    .addComponent(jLabel7)
                    .addComponent(agregarCondenaBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearBtn)
                    .addComponent(cancelarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarDelincuenteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarDelincuenteBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel)delincuentesTable.getModel();
        DelincuentesDAL dDAL = new DelincuentesDAL();
        String codigoDelincuente = delincuentesCombo.getSelectedItem().toString();
        Delincuente delincuente = dDAL.getPorCodigo(codigoDelincuente);
        model.addRow(new Object[] { delincuente.getCodigo(), delincuente.getNombre(), delincuente.getCodigoBanda(), delincuente.getDetenido()});
        loadDelincuentes();
    }//GEN-LAST:event_agregarDelincuenteBtnActionPerformed

    private void crearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearBtnActionPerformed
        
        try{
            SimpleDateFormat df = new SimpleDateFormat("yyyy/MM/dd");
            java.util.Date fecha = df.parse(fechaTextField.getText()); 
        
        
        AsaltosDAL aDAL = new AsaltosDAL();
        DefaultTableModel model = (DefaultTableModel)delincuentesTable.getModel();
        ArrayList<String> delincuentes = new ArrayList<>();
        for(int i = 0; i < delincuentesTable.getRowCount(); i++)
        {
            delincuentes.add(model.getValueAt(i, 0).toString());
        }
        if("Guardar".equals(crearBtn.getText()))
        {
            aDAL.guardar(asaltoId, fechaTextField.getText(), JuecesCombo.getSelectedItem().toString()
                , sucursalesCombo.getSelectedItem().toString(), delincuentes);
        }
        else
        {
        aDAL.crear(fechaTextField.getText(), JuecesCombo.getSelectedItem().toString()
                , sucursalesCombo.getSelectedItem().toString(), delincuentes);        
        }
        
        if(condenasTable.getRowCount() > 0)
        {
            ArrayList<Condena> condenas = new ArrayList<>();            
            for(int i = 0; i < condenasTable.getRowCount(); i++)
            {                
                DateFormat format = new SimpleDateFormat("yyyy-mm-dd", Locale.ENGLISH);
                                
                String codigoDelincuente = condenasTable.getValueAt(i, 0).toString();
                String asalto = condenasTable.getValueAt(i, 0).toString();
                String fechaDeInicio = condenasTable.getValueAt(i, 0).toString();
                Date fInicioDate = new Date(2016, 10,14);
                try {
                     fInicioDate = (Date)format.parse(fechaDeInicio);
                } catch (ParseException ex) {
                    Logger.getLogger(AsaltosAddFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                String fechaFin = condenasTable.getValueAt(i, 0).toString();
                Date fFinDate = new Date(2016, 10,14);
                
                try {
                    fFinDate = (Date) format.parse(fechaDeInicio);
                } catch (ParseException ex) {
                    Logger.getLogger(AsaltosAddFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                                
                Condena condena = new Condena(codigoDelincuente, asaltoId,
                        fInicioDate, fFinDate);
                
            }
        }       
        setVisible(false);
        dispose();
        } catch (ParseException ex) {
            
            JOptionPane.showMessageDialog(this, "Error en el campo fecha, debe tener la siguiente estructura 'yyyy/mm/dd'","Error", JOptionPane.ERROR_MESSAGE);
            
        }
        
        
        
    }//GEN-LAST:event_crearBtnActionPerformed

    private void quitarDelincuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarDelincuenteActionPerformed
        DefaultTableModel model = (DefaultTableModel)delincuentesTable.getModel();
        model.removeRow(delincuentesTable.getSelectedRow());
        loadDelincuentes();
    }//GEN-LAST:event_quitarDelincuenteActionPerformed

    private void quitarCondenaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarCondenaBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel)condenasTable.getModel();
        model.removeRow(condenasTable.getSelectedRow());        
    }//GEN-LAST:event_quitarCondenaBtnActionPerformed

    private void agregarCondenaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCondenaBtnActionPerformed
        CondenaAddFrame caf = new CondenaAddFrame(asaltoId); 
        caf.setVisible(true);        
    }//GEN-LAST:event_agregarCondenaBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsaltosAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsaltosAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsaltosAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsaltosAddFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsaltosAddFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JuecesCombo;
    private javax.swing.JButton agregarCondenaBtn;
    private javax.swing.JButton agregarDelincuenteBtn;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JTable condenasTable;
    private javax.swing.JButton crearBtn;
    private javax.swing.JComboBox<String> delincuentesCombo;
    private javax.swing.JTable delincuentesTable;
    private javax.swing.JTextField fechaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton quitarCondenaBtn;
    private javax.swing.JButton quitarDelincuente;
    private javax.swing.JComboBox<String> sucursalesCombo;
    // End of variables declaration//GEN-END:variables
}
