/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfa.bancos.Panels;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pfa.bancos.dal.BandasDAL;
import pfa.bancos.dal.DelincuentesDAL;
import pfa.bancos.dal.JuecesDAL;
import pfa.bancos.model.Banda;
import pfa.bancos.model.Delincuente;

/**
 *
 * @author Brian
 */
public class BandasAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form BandasAdminPanel
     */
    public BandasAdminPanel() {
        initComponents();
        loadBandas();
        
    }
    public BandasAdminPanel(int rol) {
        initComponents();
        loadBandas();
        editarBtn.setVisible(false);
        eliminarBtn.setVisible(false);
        agregarBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bandasTable = new javax.swing.JTable();
        editarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();

        agregarBtn.setText("Agregar");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Bandas");

        bandasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nro Miembros"
            }
        ));
        jScrollPane1.setViewportView(bandasTable);

        editarBtn.setText("Editar");
        editarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtnActionPerformed(evt);
            }
        });

        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(agregarBtn)))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarBtn)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(agregarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarBtn)
                    .addComponent(eliminarBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel)bandasTable.getModel();
        BandasDAL bDAL = new BandasDAL();

        String codigoBanda = bandasTable.getValueAt(bandasTable.getSelectedRow(), 0).toString();
        Banda banda = bDAL.obtenerBanda(codigoBanda);
        
        BandasAddFrame adf = new BandasAddFrame(banda);
        adf.setVisible(true);        
        //bDAL.eliminar(codigoJuez);
    }//GEN-LAST:event_editarBtnActionPerformed

    public void loadBandas()
    {
        BandasDAL bDAL = new BandasDAL();
        DefaultTableModel model = (DefaultTableModel)bandasTable.getModel();
        model.setRowCount(0);
        for(Banda entidad : bDAL.obtenerBandas())
        {
            model.addRow(new Object[] { entidad.getCodigoBanda(), entidad.getNroDeMiembros()});
        } 
    }
    
    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
         DefaultTableModel model = (DefaultTableModel)bandasTable.getModel();
         BandasDAL bDAL = new BandasDAL();

        String codigoBanda = bandasTable.getValueAt(bandasTable.getSelectedRow(), 0).toString();
        int reply = JOptionPane.showConfirmDialog(null, "¿Desea eliminar la sucursal seleccionada?", "Sucursales", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            bDAL.eliminar(codigoBanda);
            loadBandas();
        }
    }//GEN-LAST:event_eliminarBtnActionPerformed

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        BandasAddFrame adf = new BandasAddFrame();
        adf.setVisible(true);
    }//GEN-LAST:event_agregarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JTable bandasTable;
    private javax.swing.JButton editarBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
