/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfa.bancos.Panels;

import com.sun.xml.internal.ws.policy.sourcemodel.ModelNode;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pfa.bancos.dal.ContratacionesDAL;
import pfa.bancos.dal.VigilantesDAL;
import pfa.bancos.model.Contratacion;
import pfa.bancos.model.Vigilante;

/**
 *
 * @author Brian
 */
public class ContratacionesAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form ContratacionesAdminPanel
     */
    public ContratacionesAdminPanel() {
        initComponents();
        
        ArrayList<Vigilante> v= new VigilantesDAL().getVigilantes();
        jComboBox1.addItem("Todos");
        for(Vigilante vigilante :v){            
          jComboBox1.addItem(vigilante.getCodigo());
        }
                
        //jComboBox1
    }
    public ContratacionesAdminPanel(String codigo) {
        initComponents();        
        
        jComboBox1.addItem(codigo);
        jComboBox1.getItemAt(1).valueOf(1);
        aceptarBtn.doClick(1);
        aceptarBtn.setVisible(true);
        agregarBtn.setVisible(false);       
        eliminarBtn.setVisible(false);

    }
    public ContratacionesAdminPanel(int rol) {
        initComponents();
        
        ArrayList<Vigilante> v= new VigilantesDAL().getVigilantes();
        jComboBox1.addItem("Todos");
        for(Vigilante vigilante :v){            
          jComboBox1.addItem(vigilante.getCodigo());
        }
        agregarBtn.setVisible(false);       
        eliminarBtn.setVisible(false);
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        eliminarBtn = new javax.swing.JButton();
        agregarBtn = new javax.swing.JButton();
        aceptarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setText("Vigilantes:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });

        agregarBtn.setText("Agregar");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        aceptarBtn.setText("Aceptar");
        aceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sucursal", "Vigilante", "Arma", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(agregarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aceptarBtn)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addGap(13, 13, 13)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceptarBtn))
                .addGap(287, 287, 287)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarBtn)
                    .addComponent(agregarBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(41, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        ContratacionesAddFrame caf = new ContratacionesAddFrame();
        caf.setVisible(true);
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         aceptarBtn.doClick(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void aceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        for (int i = 0; i < jTable1.getRowCount(); i++) {
           model.removeRow(i);
           i-=1;
        }
        if(jComboBox1.getSelectedItem().toString()=="Todos"){
            ContratacionesDAL cDAL = new ContratacionesDAL();        
            //DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            for(Contratacion contratacion : cDAL.getContrataciones())
            {
                model.addRow(new Object[] { contratacion.getCodigoSucursal(), contratacion.getCodigoVigilante(), contratacion.getArmas(),contratacion.getFecha()});
            }
        }else{
            ContratacionesDAL cDAL = new ContratacionesDAL();        
            //DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            for(Contratacion contratacion : cDAL.getContratacionesPorCodigoVigilante(jComboBox1.getSelectedItem().toString()))
            {
                model.addRow(new Object[] { contratacion.getCodigoSucursal(), contratacion.getCodigoVigilante(), contratacion.getArmas(),contratacion.getFecha()});
            } 
            
        }
        
        
        
 
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarBtnActionPerformed

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        int rowIndex = jTable1.getSelectedRow();
        String codigo = (String) jTable1.getValueAt(rowIndex, 1);                     
        Date fecha = (Date) jTable1.getValueAt(rowIndex, 3); 
        int reply = JOptionPane.showConfirmDialog(null, "¿Desea eliminar la contratacion seleccionada?", "Contrataciones", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {            
           ContratacionesDAL cDAL = new ContratacionesDAL();
           cDAL.eliminar(codigo,fecha);
      
           
        }     
        
        
        aceptarBtn.doClick(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBtn;
    private javax.swing.JButton agregarBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
