/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfa.bancos.Panels;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pfa.bancos.dal.EntidadesBancariasDAL;
import pfa.bancos.dal.SucursalDAL;
import pfa.bancos.model.EntidadBancaria;
import pfa.bancos.model.Sucursal;

/**
 *
 * @author Brian
 */
public class SucursalesAdministrarPanel extends javax.swing.JPanel {

    /**
     * Creates new form SucursalesAdministrar
     */
    public SucursalesAdministrarPanel() {
        initComponents();
        
        EntidadesBancariasDAL ebDAL = new EntidadesBancariasDAL();
        ArrayList<EntidadBancaria> entidades = ebDAL.obtenerEntidades();
        
        for(EntidadBancaria entidad : entidades)
        {
            entidadesCombo.addItem(entidad.getCodigo());
        }
        jButton1.doClick(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        entidadesCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        eliminarBtn = new javax.swing.JButton();
        editarBtn = new javax.swing.JButton();
        agregarBtn = new javax.swing.JButton();

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        entidadesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entidadesComboActionPerformed(evt);
            }
        });

        jLabel1.setText("Entidad Bancaria:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Domicilio", "Empleados"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        }

        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });

        editarBtn.setText("Editar");
        editarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBtnActionPerformed(evt);
            }
        });

        agregarBtn.setText("Agregar");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entidadesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(agregarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(entidadesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarBtn)
                    .addComponent(editarBtn)
                    .addComponent(agregarBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SucursalDAL sDAL = new SucursalDAL();
        String codigo = entidadesCombo.getSelectedItem().toString();
        ArrayList<Sucursal> sucursales = sDAL.getSucursalesPorCodigoEntidad(codigo);
        
        jTable1.removeAll();
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        if (jTable1.getRowCount() > 0) {
            for (int i = jTable1.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }
        
        for(Sucursal sucursal : sucursales)
        {
            model.addRow(new Object[] { sucursal.getCodigo(), sucursal.getDomicilio(), sucursal.getNroEmpleados() });
        }         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        String codigo = entidadesCombo.getSelectedItem().toString();
        SucursalesAddFrame adf = new SucursalesAddFrame(codigo);
        adf.setVisible(true);
        
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void editarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBtnActionPerformed
        int rowIndex = jTable1.getSelectedRow();
        String codigo = jTable1.getValueAt(rowIndex, 0).toString();                    
        SucursalDAL sDAL = new SucursalDAL();
        SucursalesAddFrame saf = new SucursalesAddFrame(sDAL.getSucursalPorCodigo(codigo));
        saf.setVisible(true);
    }//GEN-LAST:event_editarBtnActionPerformed

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        int rowIndex = jTable1.getSelectedRow();
        String codigo = jTable1.getValueAt(rowIndex, 0).toString();                     
        int reply = JOptionPane.showConfirmDialog(null, "¿Desea eliminar la sucursal seleccionada?", "Sucursales", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {            
           SucursalDAL sDAL = new SucursalDAL();
           sDAL.eliminar(codigo);
        }
        jButton1.doClick(1);
    }//GEN-LAST:event_eliminarBtnActionPerformed

    private void entidadesComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entidadesComboActionPerformed
        
        jButton1.doClick(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_entidadesComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JButton editarBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JComboBox<String> entidadesCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
