/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfa.bancos.Panels;

import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import pfa.bancos.dal.UsuariosDAL;
import pfa.bancos.model.Usuario;

/**
 *
 * @author Alejandro
 */
public class UsuariosAdminPanel extends javax.swing.JPanel {

    
         
         
  
    
    
    /**
     * Creates new form UsuariosAdminPanel
     */
    public UsuariosAdminPanel() {
        initComponents();
        
        Privilegios_ComboBox.removeAllItems();
        Privilegios_ComboBox.addItem ("");
        Privilegios_ComboBox.addItem ("Administrador");
        Privilegios_ComboBox.addItem ("Investigador");  
        Privilegios_ComboBox.addItem ("Vigilante");
        Privilegios_ComboBox.setVisible(false);
        jLabel1.setVisible(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Privilegios_ComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jButton2.setText("Editar");
        jButton2.setActionCommand("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Crear");
        jButton3.setActionCommand("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );

        Privilegios_ComboBox.setToolTipText("");
        Privilegios_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Privilegios_ComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Privilegios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Privilegios_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Privilegios_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Privilegios_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Privilegios_ComboBoxActionPerformed
        
         
        
        if("Vigilante".equals(Privilegios_ComboBox.getSelectedItem())){
            
            removeCurrentPanel();
            VigilantesAddPanel vig = new VigilantesAddPanel();         
            jPanel1.setLayout(new BorderLayout());
            jPanel1.add(vig, BorderLayout.CENTER);
            jPanel1.revalidate();
       
            
        }else if("Investigador".equals(Privilegios_ComboBox.getSelectedItem())){
            
            removeCurrentPanel();
           
            AdminInvestADDPanel adminvs = new AdminInvestADDPanel(2);         
            jPanel1.setLayout(new BorderLayout());
            jPanel1.add(adminvs, BorderLayout.CENTER);
            jPanel1.revalidate();
        }else if("Administrador".equals(Privilegios_ComboBox.getSelectedItem())){
            
            removeCurrentPanel();
           
            AdminInvestADDPanel adminvs = new AdminInvestADDPanel(1);         
            jPanel1.setLayout(new BorderLayout());
            jPanel1.add(adminvs, BorderLayout.CENTER);
            jPanel1.revalidate();    
            
        }else{
            removeCurrentPanel();
            jPanel1.revalidate();
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Privilegios_ComboBoxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        removeCurrentPanel();
        Privilegios_ComboBox.setVisible(true);
        jLabel1.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        removeCurrentPanel();
        Privilegios_ComboBox.setVisible(false);  
        jLabel1.setVisible(false);
        UsuariosDAL usDAL = new UsuariosDAL();
        UsuariosViewerPanel uvp = new UsuariosViewerPanel(usDAL.getUsuarios());        
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(uvp, BorderLayout.CENTER);
        jPanel1.revalidate();    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    private void removeCurrentPanel()
    {
        jPanel1.removeAll();
    }
    public void actualizar() {
        
        jButton2.doClick(1);
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Privilegios_ComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
