/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfa.bancos.Panels;

import javax.swing.table.DefaultTableModel;
import pfa.bancos.dal.VigilantesDAL;
import pfa.bancos.model.Vigilante;

/**
 *
 * @author Brian
 */
public class VigilantesAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form VigilantesAdminP
     */
    public VigilantesAdminPanel() {
        initComponents();
        
        VigilantesDAL vDAL = new VigilantesDAL();
        DefaultTableModel model = (DefaultTableModel)vigilantesTable.getModel();
        for(Vigilante vigilante : vDAL.getVigilantes())
        {
            model.addRow(new Object[] { vigilante.getCodigo(), vigilante.getNombre(), vigilante.getEdad() });
        }
    }
    public VigilantesAdminPanel(int rol) {
        initComponents();
        
        VigilantesDAL vDAL = new VigilantesDAL();
        DefaultTableModel model = (DefaultTableModel)vigilantesTable.getModel();
        for(Vigilante vigilante : vDAL.getVigilantes())
        {
            model.addRow(new Object[] { vigilante.getCodigo(), vigilante.getNombre(), vigilante.getEdad() });
        }
        agregarBtn.setVisible(false);
        eliminarBtn.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        agregarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vigilantesTable = new javax.swing.JTable();
        eliminarBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Vigilantes");

        agregarBtn.setText("Agregar");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        vigilantesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Edad"
            }
        ));
        jScrollPane1.setViewportView(vigilantesTable);

        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eliminarBtn)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregarBtn)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(agregarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        VigilantesAddFrame vaf = new VigilantesAddFrame();
        vaf.setVisible(true);
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel)vigilantesTable.getModel();
        VigilantesDAL vDAL = new VigilantesDAL();

        String codigoJuez = vigilantesTable.getValueAt(vigilantesTable.getSelectedRow(),0).toString();
        vDAL.eliminar(codigoJuez);
        model.removeRow(vigilantesTable.getSelectedRow());
    }//GEN-LAST:event_eliminarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable vigilantesTable;
    // End of variables declaration//GEN-END:variables
}
